# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20160528_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='./myapp/static/images/store_images/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='./myapp/static/images/brand_images/'),
        ),
    ]
